export const data=[
    {
        id:1,
        Name:"suresh",
        age:25,
        city:"mysore",
        image:"https://i.pinimg.com/474x/a2/94/fe/a294feeaac9a21d98701d31b591e94d7.jpg"
    },
    {
        id:2,
        Name:"loki",
        age:28,
        city:"bangalore",
        image:"https://cdn.statusqueen.com/dpimages/thumbnail/Love_Dp-2918.jpg" 
    },
    {
        id:3,
        Name:"jaggu",
        age:38,
        city:"hassan",
        image:"https://wallpaperaccess.com/full/2213424.jpg" 
    },
    {
        id:4,
        name:"shiva",
        age:36,
        city:"mangalore",
        image:"https://wallpapers.com/images/hd/cool-profile-pictures-neon-masked-man-4eqatw6nyulbbtex-2.jpg" 
    },
    {
        id:5,
        Name:"ranju",
        age:32,
        city:"bijapur",
        image:"https://bestprofilepictures.com/wp-content/uploads/2022/07/Badass-Anime-Picture-For-Wallpaper-576x1024.jpg" 
    },
    {
        id:6,
        Name:"vicky",
        age:31,
        city:"hubli",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA_SpUNGO-_BWCqkVDqpgFu8xiuUViq-416hv14VMzrm3LG29jv5t_ibcT6s5nVVGmw6I&usqp=CAU" 
    },
    {
        id:7,
        Name:"raki",
        age:36,
        city:"udupi",
        image:"https://images.unsplash.com/photo-1628563694622-5a76957fd09c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aW5zdGFncmFtJTIwcHJvZmlsZXxlbnwwfHwwfHw%3D&w=1000&q=80" 
    },
    {
        id:8,
        Name:"ramu",
        age:28,
        city:"mandya",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSLUCXF1f1tUZGubeXKwRJdXrSqZOAchLBAeEm_j87PK0scLxIj6YJe2kmsLRx23KUFwo&usqp=CAU"
    },
    {
        id:9,
        Name:"naga",
        age:30,
        city:"goa",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzHQv_th9wq3ivQ1CVk7UZRxhbPq64oQrg5Q&usqp=CAU" 
    },
    {
        id:10,
        Name:"chethu",
        age:38,
        city:"munnar",
        image:"https://sohohindi.in/wp-content/uploads/2022/06/94_sad-dp-300x200.png" 
    },

]